### ISSUE TITLE
Use Firefox browser style for panel

### ISSUE THREAD

**Issue by ssokolow** [ehsan/popup-reporter#7]
Firefox allows third-party browser/page action panels to use the widget styling developed for Firefox-internal ones and doing so helps to lend an air of professionalism to your extension.

Here's an example of how such a redesigned version could look.

![dysgo7juqaag1gv](https://user-images.githubusercontent.com/46915/37499881-ad307724-289c-11e8-81ce-191aa7c8401e.jpg)

(Sorry for it being a JPEG. I forgot to save the original PNG, Twitter converted it, and I don't have time to re-take it right now.)

While the Components section of the [Photon Design System](https://design.firefox.com/photon/) guidelines currently only offers screenshots, trusting you to figure out `chrome://browser/content/extension.css` yourself, the old, incomplete [Firefox Style Guide](https://firefoxux.github.io/StyleGuide/#/navigation) page *does* offer HTML samples that you can poke at.

(You can also use Ctrl+Alt+Shift+I to open up a browser-level DOM inspector, toggle the toolbar button which prevents panels from closing when they lose focus, and then poke at Firefox's own popups to see how they're built.)

You'll need to set `"browser_style": true` in the `browser_action` or `page_action` block of your manifest to get the requisite CSS included, but then you can produce a popup like that using simple markup.

Here's the HTML I quickly hacked together to take that mockup screenshot:

```html
<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8">
    <style>
      /* Remove spurious scrollbar */
      html { max-width: calc(100% - 1px); }

      /* Override the default two-column layout for labels and fields
         to work around the long title for the multi-line text field. */
      .panel-formElements-item {
        flex-direction: column !important;
        align-items: start !important;
      }
      .panel-formElements-item label {
        text-align: left;
        white-space: nowrap;  /* Keep "(optional)" from getting word-wrapped */
      }
      input[type="text"], textarea {
        margin-left: 1.2em;  /* Indent for a more <dl>-style look */
      }

      /* Unify the appearance of single- and multi-line text fields */
      input[type="text"], textarea {
        margin-top: 1ex;
        width: 95%;
        -moz-appearance: textfield-multiline;
      }
    </style>
  </head>
  <body>
    <div class="panel">
        <div class="panel-section panel-section-header">
            <div class="text-section-header">Report In-Page Popup</div>
        </div>
        <div class="panel-section panel-section-formElements">
            <div class="panel-formElements-item browser-style">
                <label for="url" accesskey="u"><u>U</u>RL of Page:</label>
                <input type="text" name="url" id="url" />
            </div>
            <div class="panel-formElements-item">
                <label for="desc" accesskey="d">What were you <u>d</u>oing at the time? (optional)</label>
                <textarea id="desc" name="desc"></textarea>
            </div>
        </div>
        <div class="panel-section panel-section-footer">
            <div class="panel-section-footer-button default">Send Report</div>
        </div>
    </div>
  </body>
</html>

```

**Comment by ehsan** [comment]
I think this is mostly addressed now.  Please check out the new version of the extension and let me know if there's anything left here to do.  Thanks!

**Comment by ssokolow** [comment]
Things are a bit messy for me right now, but I'll check it when I can free up enough time.

**Comment by ssokolow** [comment]
Sorry for the delay. This got pushed to the back of a big pile of TODOs.

The new design is much better, though I still see two problems:

1. I'm just left hoping that my submissions are actually going through rather than tripping over some aspect of my stack of ad-blocking and privacy-preserving stuff, because I see no confirmation of success after clicking "Report this Page".

2. I still think it's tacky and pointless to use ad-like [copy](https://en.wikipedia.org/wiki/Copy_(written)) to encourage people to report popups in a panel they can only reach by installing the extension and then clicking the page action. (If they get that far and aren't already sold on the idea of reporting popups, you've got much bigger problems.)
